### ISSUE TITLE
Problem with system theme in 18.10.

### ISSUE THREAD

**Issue by aclough** [Gekkio/gnome-session-xmonad#11]
I recently made a fresh install of 18.10 on a laptop and used your PPA to install the gnome-session-xmonad which I was able to enter with my previous xmonad.hs and which works in most respects.  However, Ubuntu's system theme is not present and the theme seems to be the default.  When I try to start up gnome-tweaks to look into the issue it dies with this traceback:

`WARNING : Shell not installed or running
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 217, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtweak/app.py", line 30, in do_activate
    self.win = Window(self, model)
  File "/usr/lib/python3/dist-packages/gtweak/tweakview.py", line 38, in __init__
    self._model.load_tweaks(self)
  File "/usr/lib/python3/dist-packages/gtweak/tweakmodel.py", line 104, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_general.py", line 14, in <module>
    _shell_not_ubuntu = _shell.mode != 'ubuntu'
AttributeError: 'NoneType' object has no attribute 'mode'
`

In the normal Ubuntu session everything is as it should be.

**Comment by Gekkio** [comment]
That crash was a gnome-tweaks bug that was fixed in gnome-tweaks 3.30.2-0ubuntu1 (December 2018). More info: https://bugs.launchpad.net/ubuntu/+source/gnome-tweaks/+bug/1799459

Now that gnome-tweaks works once again, it should be easy to make sure the theme is correct. Please reopen this issue and/or file a new one if you still encounter problems :smiley:
